steps:
  - name: "Build Raspberry Pi Pico firmware"
    docker: "intmain/microci_raspberry_pico:latest"
    plugin:
      name: raspberry_pico
      board: pico # pico | pico_w | pico2 | pico2_w
      bash: |
        rm -rf build
        # Configure and generate the build files into a 'build' directory
        cmake -S . -B build
        # Compile the project using the generated build files
        cmake --build build

