=== GPIO blink

The code structure is the same across boards, but the LED connection is not.
The correct pin matters.
A call such as `gpio_put(25, 1)` may work on one board and fail on another, because the onboard LED is not always connected directly to the main microcontroller GPIO.
On the Pico 2 W, for example, the LED is routed through the wireless chip instead of the RP2350 GPIO pins.

For that reason, the examples in this section keep the same structure while adapting the pin selection for each board.


// * PICO_DEFAULT_LED_PIN
// * CYW43_WL_GPIO_LED_PIN
// * PICO_DEFAULT_WS2812_PIN

For this example you need the following files:

* `blink_simple.c` - C source code
* `CMakeLists.txt` - Configuration file used by the CMake meta-build system
* `.microCI.yml` - Pipeline

Once you have these three files in a folder execute:

[,shell]
----
microCI | bash
----

==== RP2040

===== blink_simple.c

[source,c]
----
include::../examples/blink_rp2040/blink_simple.c[]
----

===== CMakeLists.txt

[source,cmake]
----
include::../examples/blink_rp2040/CMakeLists.txt[]
----

===== .microCI.yml

[source,yaml]
----
include::../examples/blink_rp2040/.microCI.yml[]
----


==== RP2350

===== blink_simple.c

[source,c]
----
include::../examples/blink_rp2350/blink_simple.c[]
----

===== CMakeLists.txt

[source,cmake]
----
include::../examples/blink_rp2350/CMakeLists.txt[]
----

===== .microCI.yml

[source,yaml]
----
include::../examples/blink_rp2350/.microCI.yml[]
----
