name: Execute microCI pipeline

on: [push]

permissions:
  contents: write

jobs:
  execute-docker:
    runs-on: ubuntu-latest
#    container:
#      image: debian:trixie-slim
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      # - name: Install prerequisites
      #   run: |
      #     apt-get update
      #     apt-get install -y --no-install-recommends curl ca-certificates openssh-client

      - name: Run microCI
        run: |
          curl -fsSL github.com/geraldolsribeiro/microci/releases/download/latest/microCI -o microCI
          chmod 755 ./microCI
          mkdir -p ~/.ssh/
          touch ~/.ssh/config
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N "" -q
          ./microCI | bash

      - name: Save Multiple Outputs
        uses: actions/upload-artifact@v5
        with:
          name: multi-artifact
          path: |
            _book/Gentle_Introduction_to_Embedded_Software_with_microCI.pdf

      - name: 'Pre-Release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          prerelease: true
          name: Latest
          files: |
            _book/Gentle_Introduction_to_Embedded_Software_with_microCI.pdf
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
